Repository osamhack2020/WEB_mindpill_mindpill, pull requests merged in 2020-10, with the labels that each got.

#11 clo3olb/feature/join page
  .prettierrc.js
  frontend/assets/scss/basic.scss
  frontend/assets/scss/input.scss
  frontend/assets/scss/styles.scss
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/assets/css/styles.css
  frontend/src/components/Input.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/components/SelectBySearch.tsx
  frontend/src/pages/Join.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/Login.tsx
  package-lock.json
  package.json
Labels: enhancement

#7 데이터베이스 패키지
  .gitignore
  Makefile
  backend/cmd/mindpill/main.go
  backend/configs/database.go
  backend/internal/database/database.go
  backend/internal/ids/id.go
  backend/setup.go
  ent/generate.go
  ent/schema/admin.go
  ent/schema/counselor.go
  ent/schema/file.go
  ent/schema/group.go
  ent/schema/manager.go
  ent/schema/message.go
  ent/schema/note.go
  ent/schema/room.go
  ent/schema/user.go
  go.mod
  go.sum
Labels: enhancement

#13 초기 데이터베이스 셋업 기능
  Makefile
  backend/cmd/setup-database/main.go
Labels: enhancement

#22 Frontend: 상담페이지 URL을 이용한 탭기능 구현
  frontend/assets/scss/basic.scss
  frontend/assets/scss/chat.scss
  frontend/src/App.tsx
  frontend/src/pages/Chat.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/routes.tsx
Labels: enhancement

#10 사용자 관련 패키지 및 API
  Makefile
  backend/cmd/mindpill/main.go
  backend/configs/server.go
  backend/handlers/api/auth.go
  backend/handlers/api/error.go
  backend/handlers/api/helpers.go
  backend/handlers/api/user.go
  backend/internal/ids/id.go
  backend/internal/ids/log.go
  backend/internal/tokens/helper.go
  backend/internal/tokens/log.go
  backend/internal/tokens/token.go
  backend/internal/tokens/token_test.go
  backend/router.go
  backend/run.go
  docs/api.md
  docs/api/index.md
  ent/schema/rank.go
  ent/schema/token.go
  ent/schema/user.go
  go.mod
  go.sum
Labels: enhancement

#35 상담하기 페이지 가상API를 사용한 기본 플로우 구성
  frontend/assets/scss/chat.scss
  frontend/src/pages/Chat.tsx
  frontend/src/tempDatabase.tsx
Labels: enhancement

#38 Component 함수 컴포넌트로 변환
  frontend/src/components/Input.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/components/SelectBySearch.tsx
Labels: enhancement

#39 가상 로그인 구현 및 라우팅 정보 수정
  frontend/assets/scss/basic.scss
  frontend/src/App.tsx
  frontend/src/pages/Counsel.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Join.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Manage.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/routes.tsx
  frontend/src/tempDatabase.tsx
Labels: enhancement

#40 상담 페이지 - 지휘관에게 쪽지 기능 추가, 메모 기능 추가
  frontend/assets/scss/basic.scss
  frontend/assets/scss/counsel.scss
  frontend/assets/scss/input.scss
  frontend/assets/scss/manage.scss
  frontend/src/App.tsx
  frontend/src/components/CounselToolbox.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/pages/Counsel.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/tempDatabase.tsx
Labels: enhancement

#44 ent: User edge index가 Unique 하지 않도록 설정
  ent/schema/token.go
Labels: bug

#45 docs: User API 문서 개선
  docs/api.md
Labels: documentation

#55 전체 CSS 및 레이아웃 변경
  Makefile
  frontend/assets/scss/comp-menuDropdown.scss
  frontend/assets/scss/mobile-basics.scss
  frontend/assets/scss/mobile-input.scss
  frontend/assets/scss/mobile-layout.scss
  frontend/assets/scss/mobile-styles.scss
  frontend/assets/scss/page-404.scss
  frontend/assets/scss/page-currentRoom.scss
  frontend/assets/scss/page-join.scss
  frontend/assets/scss/page-login.scss
  frontend/assets/scss/page-rightSideBarProfile.scss
  frontend/assets/scss/page-template.scss
  frontend/assets/scss/reset.scss
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Input.tsx
  frontend/src/components/MenuDropdown.tsx
  frontend/src/pages/CounselRooms.tsx
  frontend/src/pages/CurrentRoom.tsx
  frontend/src/pages/Friends.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Join.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Manage.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/routes.tsx
Labels: enhancement

#46 채팅 기능 추가
  .babelrc
  .prettierrc.js
  Makefile
  backend/handlers/api/chat.go
  backend/handlers/api/note.go
  backend/handlers/api/user.go
  backend/internal/chat/client.go
  backend/internal/chat/decoder.go
  backend/internal/chat/error_message.go
  backend/internal/chat/media_message.go
  backend/internal/chat/message.go
  backend/internal/chat/pool.go
  backend/internal/chat/session.go
  backend/internal/chat/text_message.go
  backend/internal/chat/timestamp_message.go
  backend/internal/chat/uid_message.go
  backend/internal/chat/util.go
  backend/internal/tokens/token.go
  backend/router.go
  docs/chat.md
  ent/schema/note.go
  frontend/src/components/ChatRoom.tsx
  frontend/src/lib/chat/buffer.ts
  frontend/src/lib/chat/chat.ts
  frontend/src/lib/chat/decode.test.ts
  frontend/src/lib/chat/decode.ts
  frontend/src/lib/chat/driver.ts
  frontend/src/lib/chat/encode.ts
  frontend/src/lib/chat/event.ts
  frontend/src/lib/chat/index.ts
  frontend/src/lib/chat/message.ts
  frontend/src/lib/chat/room.ts
  frontend/src/pages/ChatTest.tsx
  frontend/src/routes.tsx
  go.mod
  go.sum
  package-lock.json
  package.json
  webpack.client.js
  webpack.common.js
  webpack.config.js
  webpack.server.js
Labels: enhancement
